/**
 * File containing all the useful and usable functions to use througouht Lamatomic
 */
import Vue from 'vue'

/**
 * Mounts Vue Component programmatically and returns HTML generated by Vue
 *
 * @param {VueComponent} component Component to mount
 * @param {Object} props Props to use for the given component
 * @param {Object} slots [Optional] Slots eventually populate -> { default: 'My slot content', 'custom-slot': "My custom slot content"}
 *
 * @returns {string} HTML Component rendering
 */
export const getMountedComponent = (
    component: any,
    props: Object,
    slots: Object = {}
): string => {
    const VueCmp = Vue.extend(component)
    const instance = new VueCmp({
        propsData: {
            ...props
        }
    })

    if (Object.keys(slots).length > 0) {
        for (const [key, value] of Object.entries(slots)) {
            instance.$slots[key] = [instance.$createElement('span', [value])]
        }
    }

    return instance.$mount().$el.outerHTML
}

/**
 * Get a random string on given length
 *
 * @param {number} length Length of the generated string
 *
 * @return {string} Random generated string
 */
export const getRandom = (length: number = 5): string => {
    return Math.random()
        .toString(36)
        .substr(2, length)
}
